#!/usr/bin/env node

var fg = require('./index'),
    generateCharmap = require('./generateCharmap.js'),
    fs = require('fs'),
    path = require('path');

if (process.argv.length < 4) {
  console.log('Usage: webfont-generator <input folder> <output folder> -m generate charmap');
  return;
}

var inputDir = path.resolve(process.argv[2]);
var outputDir = path.resolve(process.argv[3]);
var createCharmap = (process.argv[4] === '-m' ? true : false);

function loadConfig() {
    return fs.readFileSync(path.join(inputDir, '/', 'config.json')).toString();
}

if(createCharmap) {
    var config = loadConfig()
    generateCharmap(config, inputDir);
}

fg.generateFont(inputDir, outputDir, function (err, result) {
  if (err) {
    console.log('Error: ' + err);
    return;
  }
  console.log('Successfully generated font from ' + inputDir);
  console.log(result);
});
